import '../../style/globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'

import Header from '@/components/header'
import Banner from '@/components/banner'


//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Compssa | Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-7xl mx-auto'>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  )
}
